name: Run Weekly

on: 
  workflow_dispatch:
  schedule:   
    - cron: "0 13 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.4
      uses: actions/setup-node@v1
      with:
        node-version: 16.4

    - name: Build
      run: |
        npm install
        npm start
